%TIDAL_DEFORMATION Vertical column strain against the tide at Windless Bight.
%
%   NOTE ON A FIXED ARTEFACT AND THE METRIC. Products produced before
%   2026-08-04 carried a tide-proportional artefact from multipass's
%   z-motion compensation treating tidal heave as platform motion; it is
%   corrected upstream by vdef.coalignPair (see 'Fixed: the
%   tide-proportional artefact' in the project README). The response
%   metric here is the joint strain = a + b*t + c*tide fit
%   (vdef.fitTideAdmittance): the admittance c and its partial
%   correlation are invariant to the choice of reference pass, unlike the
%   PLAIN correlation of strain with tide, into which the secular trend
%   aliases with a reference-dependent sign (demonstrated in
%   scripts/test_tide_admittance.m). The plain r is still printed in the
%   per-line table for continuity, but every plot, and the hinge change
%   point, reads the trend-removed partial correlation.
%
%   Builds the analysis that motivates the whole project, for every EAGER
%   2022 repeat-pass line: Windless Bight is floating, so if tidal flexure
%   strains the ice column then the vertical strain measured between repeat
%   passes should track the tide.
%
%   Every product in the 'main' pairing measures the SAME reference pass
%   against a different pass, so together they are a time series of the
%   column's state relative to that one epoch - which is exactly what is
%   wanted here, and is why this reads the main pairing rather than the
%   sequential one.
%
%   Two observables, both relative to the main pass:
%     tide   mean platform elevation of each pass (the passes sit on a
%            floating shelf, so the antenna rides the tide directly)
%     strain dh at REF_DEPTHS divided by that depth - the mean vertical
%            strain of the column between the surface and that depth
%
%   They are NOT plotted on a shared pair of axes: metres of heave and
%   dimensionless strain are different scales, and a twin y-axis invites
%   reading a correlation off the plot that the axis scaling created. They
%   get stacked panels over a common time axis, and the correlation gets
%   its own panels where it can be judged honestly.
%
%   THE ROBUSTNESS TESTS.
%   1. The tide series is IDENTICAL for every block of a line, so a
%      common-mode artefact would correlate with the same sign everywhere.
%      A sign REVERSAL along track has to come from the strain data.
%   2. The far-end blocks are also the ones whose coherence thins with
%      depth, so the correlation is computed over two column depths: 100 m,
%      where every block has near-full coverage, and 200 m, where the far
%      end is patchy. A reversal present at both is a property of the ice.
%   3. Pairs whose cross-track baseline exceeds MAX_BASELINE are dropped:
%      surface referencing does not remove topographic phase, and
%      EAGER_2022_GL2 in particular has passes tens of metres off track.
%   4. Five independent lines (EAGER_2022 and GL1-GL4). A hinge that is real
%      should appear in all of them, at consistent GEOGRAPHIC positions rather
%      than at the same distance along each line.
%
%   Outputs one 4-panel figure per line. The cross-line summary figure is
%   deliberately retired (see the note at the out_dir assignment below);
%   admittance_map.m carries the map view.
%
%   Run on the server, where the products live:
%     /opt/sw/matlab/2024b/bin/matlab -batch "run('.../tidal_deformation.m')"

addpath(fileparts(fileparts(fileparts(mfilename('fullpath')))));   % +vdef

% VVEL_SUFFIX selects which processing run to read. The default is '_v3',
% the current per-column-coaligned main-pairing build.
%
% DO NOT POINT THIS AT A SUPERSEDED BUILD BY ACCIDENT. Several generations
% exist on the server and all but one are known bad:
%   ''            group-delay coalignment estimator - injected up to
%                 8.5 ns of noise; SUPERSEDED
%   '_fine' '_seq' '_firstpass'   same estimator, other block sizes/pairings
%   '_precoalign' no coalignment at all
%   '_v2'         scalar coalignment - PRODUCED THE RETRACTED FLEXURE HINGE
%   '_v3'         per-column coalignment - current
% Figures built from the superseded generations reproduce the retracted
% hinge, complete with change-point stars, and are indistinguishable at a
% glance from a current result. Every such figure was deleted on
% 2026-08-06; one was regenerated by accident on 2026-08-19 by running
% this script with the old default, which is why the guard below exists.
% The guard is a WHITELIST of known-good builds, not a blacklist of known
% bad ones: a typo or a future superseded generation must refuse loudly
% here rather than fail late with a confusing 'no products' warning.
if ~exist('VVEL_SUFFIX','var'), VVEL_SUFFIX = '_v3'; end
KNOWN_GOOD = {'_v3'};
if ~any(strcmp(VVEL_SUFFIX, KNOWN_GOOD))
  if ~exist('ALLOW_SUPERSEDED','var') || ~ALLOW_SUPERSEDED
    error('tidal_deformation:superseded', ...
      ['VVEL_SUFFIX ''%s'' is not a known-good build (known good: %s). ' ...
       'Superseded generations reproduce the RETRACTED flexure hinge. ' ...
       'Use ''_v3'' (the current build), add a new build to KNOWN_GOOD ' ...
       'once it is validated, or set ALLOW_SUPERSEDED=true if you are ' ...
       'deliberately reproducing the artefact for the record.'], ...
      VVEL_SUFFIX, strjoin(KNOWN_GOOD, ', '));
  end
  fprintf(['*** WARNING: reading build ''%s'', which is not on the ' ...
           'known-good whitelist. Output may show the RETRACTED hinge and ' ...
           'must not be used as a current result. ***\n'], VVEL_SUFFIX);
end
vvel_dir = ['/kucresis/scratch/hoffmana_sta/vvel/2022_Antarctica_Ground/CSARP_vvel' VVEL_SUFFIX];
fprintf('reading %s\n', vvel_dir);
mp_dir   = '/cresis/dataproducts/opr_data/accum/2022_Antarctica_Ground/CSARP_multipass';
out_dir  = '/kucresis/scratch/hoffmana_sta/vvel/figures';
% gis_dir is unused now that this script emits no map: the REMA hillshade
% and grounding-line helpers went with the cross-line summary figure.
% admittance_map.m carries the map view.

PASS_NAMES = {'EAGER_2022','EAGER_2022_GL1','EAGER_2022_GL2', ...
              'EAGER_2022_GL3','EAGER_2022_GL4'};
REF_DEPTHS    = [100 200];  % [m] column depths over which strain is measured
MAIN_DEPTH    = 2;          % which of those drives the per-line panels (b), (c)
SUMMARY_DEPTH = 1;          % which drives the printed hinge table (the robust one)
MIN_OBS       = 10;         % below this a block's correlation is drawn hollow
MAX_BASELINE  = 10;         % [m] cross-track baseline above which a pair is dropped

if ~exist(out_dir,'dir'), mkdir(out_dir); end

% Palette. Blocks along a line are ORDERED -> single-hue sequential ramp.
% Lines are CATEGORIES -> validated categorical hues (5 slots, worst
% adjacent CVD dE 9.1; the sub-3:1 contrast warning on three of them is
% relieved by the legend and the printed table). The correlation map is
% POLARITY -> diverging, two poles with a neutral gray midpoint and no hue
% at the middle.
PAL = struct();
PAL.seq_anchors = [0.776 0.859 0.937; 0.419 0.682 0.839; 0.129 0.443 0.710; ...
                   0.032 0.271 0.580; 0.031 0.188 0.420];
PAL.cat = [0.165 0.471 0.839;    % #2a78d6 blue
           0.922 0.408 0.204;    % #eb6834 orange
           0.106 0.686 0.478;    % #1baf7a aqua
           0.929 0.631 0.000;    % #eda100 yellow
           0.910 0.482 0.643];   % #e87ba4 magenta
PAL.cat_mk  = {'o','s','^','d','v'};
PAL.div_neg = [0.698 0.094 0.169];   % red pole:  strain falls as the tide rises
PAL.div_mid = [0.941 0.937 0.925];   % neutral gray midpoint
PAL.div_pos = [0.165 0.471 0.839];   % blue pole: strain rises with the tide
PAL.ink      = [0 0 0];      % axis labels, tick labels, axis lines
PAL.ink_soft = [0.45 0.45 0.45];

%% Analyse every line
res = [];
for ip = 1:numel(PASS_NAMES)
  r1 = analyse_line(PASS_NAMES{ip}, vvel_dir, mp_dir, REF_DEPTHS, MAX_BASELINE);
  if isempty(r1), continue; end
  if isempty(res), res = r1; else, res(end+1) = r1; end %#ok<SAGROW>
end
assert(~isempty(res),'no lines could be analysed');

%% Per-line report and figure
for i = 1:numel(res)
  R = res(i);
  fprintf('\n===== %s =====\n', R.pass_name);
  fprintf('main pass %d (%s), %d of %d pairs used (%d dropped on cross-track baseline)\n', ...
    R.main_pass, R.main_seg, R.np_used, R.np_all, R.np_all - R.np_used);
  fprintf('tide range %.3f m\n', R.tide_range);
  fprintf('%-6s %10s %9s %9s', 'block','along[km]','lat','lon');
  for j = 1:numel(REF_DEPTHS)
    fprintf(' %7s%3.0f %7s%3.0f %6s%3.0f %10s%3.0f', 'n@', REF_DEPTHS(j), ...
      'r@', REF_DEPTHS(j), 'rp@', REF_DEPTHS(j), 'adm[ue/m]@', REF_DEPTHS(j));
  end
  fprintf('\n');
  for b = 1:R.Nblk
    fprintf('%-6d %10.2f %9.4f %9.4f', b, R.along(b)/1e3, R.lat(b), R.lon(b));
    for j = 1:numel(REF_DEPTHS)
      fprintf(' %10d %10.2f %9.2f %13.1f', R.nobs(b,j), R.r(b,j), ...
        R.rp(b,j), 1e6*R.adm(b,j));
    end
    fprintf('\n');
  end
  res(i).suffix = VVEL_SUFFIX; R.suffix = VVEL_SUFFIX;
  plot_line_figure(R, REF_DEPTHS, MAIN_DEPTH, MIN_OBS, PAL, out_dir);
end

%% Cross-line summary
fprintf('\n===== hinge position per line (change point in r_partial at %.0f m) =====\n', ...
  REF_DEPTHS(SUMMARY_DEPTH));
fprintf('%-18s %10s %9s %9s %9s %8s %8s\n', ...
  'line','along[km]','lat','lon','contrast','r_near','r_far');
for i = 1:numel(res)
  R = res(i);
  [xc, latc, lonc, contrast] = zero_crossing(R, SUMMARY_DEPTH);
  near = R.rp(1:min(3,R.Nblk), SUMMARY_DEPTH);
  far  = R.rp(max(1,R.Nblk-3):R.Nblk, SUMMARY_DEPTH);
  fprintf('%-18s %10s %9s %9s %9s %8.2f %8.2f\n', R.pass_name, ...
    numstr(xc/1e3,'%.2f'), numstr(latc,'%.4f'), numstr(lonc,'%.4f'), ...
    numstr(contrast,'%.2f'), mean(near,'omitnan'), mean(far,'omitnan'));
  res(i).xc = xc; res(i).latc = latc; res(i).lonc = lonc;
end

% The cross-line summary FIGURE is deliberately not emitted. It plotted the
% partial correlation of strain with tide, per line and in map view, which
% under correct (per-column) processing has no along-track structure and so
% says less than admittance_map.m says with the physical quantity (mm per
% metre of tide, with the GPS-curvature prediction and the located ApRES
% site). Two near-identical maps of the same relationship, on different
% metrics and different builds, is exactly what let a figure from a
% superseded build sit next to a current one and look like a scientific
% disagreement. The per-line QC figures above are kept - those are
% genuinely diagnostic - and the hinge table still prints to stdout.

%% ========================================================================
function R = analyse_line(pass_name, vvel_dir, mp_dir, REF_DEPTHS, MAX_BASELINE)
R = [];
f = dir(fullfile(vvel_dir, [pass_name '_vvel_*.mat']));
% dir() prefix-matches, so the EAGER_2022_GL* files would also answer to
% EAGER_2022; keep only the exact line
keep = false(1,numel(f));
for i = 1:numel(f)
  keep(i) = ~isempty(regexp(f(i).name, ...
    ['^' regexptranslate('escape',pass_name) '_vvel_\d+_\d+\.mat$'], 'once'));
end
f = f(keep);
if isempty(f)
  warning('no products for %s', pass_name);
  return;
end

mp_fn = fullfile(mp_dir, sprintf('%s_multipass03.mat', pass_name));
L = load(mp_fn,'pass');
Npass = numel(L.pass);
pass_elev = nan(1,Npass); pass_seg = cell(1,Npass);
for k = 1:Npass
  pass_elev(k) = mean(L.pass(k).elev,'omitnan');
  pass_seg{k}  = L.pass(k).param_pass.day_seg;
end
clear L;

sec_per_year = 365.25*86400;
np = numel(f); nd = numel(REF_DEPTHS);
sec_idx = nan(1,np); ref_idx = nan(1,np); t_sec = nan(1,np); maxbl = nan(1,np);
strain = []; along = []; lat = []; lon = [];
for i = 1:np
  o = load(fullfile(vvel_dir, f(i).name));
  sec_idx(i) = o.pass_idx_sec;
  ref_idx(i) = o.pass_idx_ref;
  maxbl(i)   = max(abs(o.baseline_y));
  if isempty(strain)
    Nblk = numel(o.S1);
    strain = nan(Nblk, np, nd);
    along = o.Along_track(:); lat = o.Latitude(:); lon = o.Longitude(:);
  end
  if ref_idx(i) ~= ref_idx(1)
    error('%s: %s is referenced to pass %d but %s is referenced to pass %d. This script assumes the "main" pairing, where every product shares one reference pass; a sequential-pairing product must not be co-located in %s.', ...
      pass_name, f(i).name, ref_idx(i), f(1).name, ref_idx(1), vvel_dir);
  end
  t_sec(i) = mean(o.GPS_time + o.delta_t_blk*sec_per_year,'omitnan');
  for b = 1:Nblk
    d  = o.depth_blk(:,b);
    ok = isfinite(d) & isfinite(o.dh_blk(:,b));
    if ~any(ok), continue; end
    for j = 1:nd
      if max(d(ok)) < REF_DEPTHS(j), continue; end
      strain(b,i,j) = interp1(d(ok), o.dh_blk(ok,b), REF_DEPTHS(j), 'linear', NaN) ...
        / REF_DEPTHS(j);
    end
  end
end

% Drop pairs that carry topographic phase from a long cross-track baseline
use = ~(isfinite(maxbl) & maxbl > MAX_BASELINE);
np_all = np;
sec_idx = sec_idx(use); ref_idx = ref_idx(use); t_sec = t_sec(use);
strain = strain(:,use,:);
if numel(t_sec) < 5
  warning('%s: only %d usable pairs after the baseline cut', pass_name, numel(t_sec));
  R = []; return;
end

[t_sec, ord] = sort(t_sec);
sec_idx = sec_idx(ord);
ref_idx = ref_idx(ord);
strain  = strain(:,ord,:);
main_pass = ref_idx(1);
tide   = pass_elev(sec_idx) - pass_elev(main_pass);
t_days = (t_sec - min(t_sec))/86400;

Nblk = size(strain,1);
r = nan(Nblk,nd); nobs = zeros(Nblk,nd);
adm = nan(Nblk,nd); adm_std = nan(Nblk,nd); rp = nan(Nblk,nd); trend = nan(Nblk,nd);
for j = 1:nd
  % The reference-invariant joint fit drives the plots and the hinge
  A = vdef.fitTideAdmittance(strain(:,:,j), t_days, tide);
  adm(:,j)     = A.admittance(:);
  adm_std(:,j) = A.admittance_std(:);
  rp(:,j)      = A.r_partial(:);
  trend(:,j)   = A.trend(:);
  % The plain correlation is kept only for the printed table (see header)
  for b = 1:Nblk
    s  = strain(b,:,j);
    ok = isfinite(s) & isfinite(tide);
    nobs(b,j) = nnz(ok);
    if nobs(b,j) < 5, continue; end
    rm = corrcoef(tide(ok), s(ok));
    r(b,j) = rm(1,2);
  end
end

R = struct('pass_name',pass_name,'main_pass',main_pass,'main_seg',{pass_seg{main_pass}}, ...
  'np_all',np_all,'np_used',numel(t_sec),'Nblk',Nblk,'along',along,'lat',lat,'lon',lon, ...
  'tide',tide,'t_days',t_days,'t_sec',t_sec,'strain',strain,'r',r, ...
  'adm',adm,'adm_std',adm_std,'rp',rp,'trend',trend, ...
  'nobs',nobs,'tide_range',max(tide)-min(tide),'xc',NaN,'latc',NaN,'lonc',NaN, ...
  'suffix','');
end

%% ========================================================================
function [xc, latc, lonc, contrast] = zero_crossing(R, j)
% Along-track position of the strongest positive-to-negative transition in
% the trend-removed tidal response (r_partial) - the hinge.
%
% NOT the first zero crossing. With the short along-track window there are
% 39 blocks per line and the per-block correlation is noisy, so the first
% crossing latches onto whichever wiggle happens to dip below zero near the
% start. This is a change-point instead: the split that maximises
% mean(r) before minus mean(r) after, which is driven by the whole profile
% rather than by one block, and which reports nothing when there is no real
% step (MIN_CONTRAST) instead of inventing a hinge.
MIN_CONTRAST = 0.5;   % the drop in mean r either side must be at least this
MIN_SIDE     = 3;     % blocks required on each side

xc = NaN; latc = NaN; lonc = NaN; contrast = NaN;
rr = R.rp(:,j);
ok = find(isfinite(rr));
n  = numel(ok);
if n < 2*MIN_SIDE, return; end
rv = rr(ok); xx = R.along(ok);

best = -inf; kbest = [];
for k = MIN_SIDE:(n-MIN_SIDE)
  d = mean(rv(1:k)) - mean(rv(k+1:end));
  if d > best, best = d; kbest = k; end
end
if isempty(kbest) || best < MIN_CONTRAST, return; end

contrast = best;
xc   = 0.5*(xx(kbest)        + xx(kbest+1));
latc = 0.5*(R.lat(ok(kbest)) + R.lat(ok(kbest+1)));
lonc = 0.5*(R.lon(ok(kbest)) + R.lon(ok(kbest+1)));
end

%% ========================================================================
function s = numstr(v, fmt)
if isfinite(v), s = sprintf(fmt, v); else, s = 'none'; end
end

%% ========================================================================
function plot_line_figure(R, REF_DEPTHS, MAIN_DEPTH, MIN_OBS, PAL, out_dir)
cmap = interp1(linspace(0,1,size(PAL.seq_anchors,1)), PAL.seq_anchors, ...
  linspace(0,1,max(R.Nblk,2)));
ink = PAL.ink; ink_soft = PAL.ink_soft;
depth_col = {PAL.cat(1,:), PAL.cat(2,:)};
depth_mk  = {'o','s'};

h = figure('Visible','off','Position',[100 100 950 1180],'Color','w');
axstyle = {'GridAlpha',0.15,'XColor',ink,'YColor',ink,'Box','off'};

ax1 = axes('parent',h,'Position',[0.10 0.775 0.73 0.175]);
plot(ax1, R.t_days, R.tide, '-', 'Color', ink_soft, 'LineWidth', 1.5); hold(ax1,'on');
plot(ax1, R.t_days, R.tide, 'o', 'MarkerSize', 7, 'MarkerFaceColor', ink, ...
  'MarkerEdgeColor','w','LineWidth',1);
grid(ax1,'on'); set(ax1, axstyle{:});
ylabel(ax1,'Platform elevation (m)','Color',ink);
title(ax1, sprintf('%s  -  tide from pass GPS elevation, relative to the main pass', ...
  R.pass_name), 'Interpreter','none','Color',ink);

ax2 = axes('parent',h,'Position',[0.10 0.535 0.73 0.175]);
hold(ax2,'on');
for b = 1:R.Nblk
  if R.nobs(b,MAIN_DEPTH) < 5, continue; end
  plot(ax2, R.t_days, 1e6*R.strain(b,:,MAIN_DEPTH), '-o', 'Color', cmap(b,:), ...
    'MarkerSize', 5, 'MarkerFaceColor', cmap(b,:), 'MarkerEdgeColor','w','LineWidth',1.5);
end
grid(ax2,'on'); set(ax2, axstyle{:});
ylabel(ax2, sprintf('Strain 0-%.0f m (\\mu\\epsilon)', REF_DEPTHS(MAIN_DEPTH)),'Color',ink);
xlabel(ax2, sprintf('Days from %s UTC', ...
  datestr(epoch_to_datenum(min(R.t_sec)),'yyyy-mm-dd HH:MM')), 'Color', ink);
title(ax2,'Vertical strain of the column, relative to the main pass','Color',ink);
cb = colorbar(ax2,'Position',[0.855 0.535 0.020 0.175]);
colormap(ax2, cmap); caxis(ax2, [R.along(1) R.along(end)]/1e3);
set(get(cb,'ylabel'),'string','Along track (km)','Color',ink);
set(cb,'XColor',ink,'YColor',ink);

% Detrended: the secular term b*t of the joint fit is removed from each
% block's series before plotting, so the line drawn IS the admittance and
% the scatter around it is what the fit actually sees (see header)
ax3 = axes('parent',h,'Position',[0.10 0.295 0.73 0.175]);
hold(ax3,'on');
for b = 1:R.Nblk
  if ~isfinite(R.adm(b,MAIN_DEPTH)), continue; end
  s  = R.strain(b,:,MAIN_DEPTH);
  ok = isfinite(s) & isfinite(R.tide);
  s_dt = s - R.trend(b,MAIN_DEPTH)*(R.t_days - mean(R.t_days(ok)));
  plot(ax3, R.tide, 1e6*s_dt, 'o', 'MarkerSize', 6, 'MarkerFaceColor', cmap(b,:), ...
    'MarkerEdgeColor','w','LineWidth',0.75);
  xf = linspace(min(R.tide(ok)), max(R.tide(ok)), 2);
  b0 = mean(s_dt(ok)) - R.adm(b,MAIN_DEPTH)*mean(R.tide(ok));
  plot(ax3, xf, 1e6*(R.adm(b,MAIN_DEPTH)*xf + b0), '-', 'Color', cmap(b,:), 'LineWidth',1.5);
end
grid(ax3,'on'); set(ax3, axstyle{:});
xlabel(ax3,'Platform elevation relative to main pass (m)','Color',ink);
ylabel(ax3, sprintf('Detrended strain 0-%.0f m (\\mu\\epsilon)', REF_DEPTHS(MAIN_DEPTH)),'Color',ink);
title(ax3,'Detrended strain against tide - the fitted lines are the admittance','Color',ink);

ax4 = axes('parent',h,'Position',[0.10 0.055 0.73 0.175]);
hold(ax4,'on');
plot(ax4, [R.along(1) R.along(end)]/1e3, [0 0], '-', 'Color', [0.75 0.75 0.75], 'LineWidth',1);
hleg = []; lbl = {};
for j = 1:numel(REF_DEPTHS)
  solid = R.nobs(:,j) >= MIN_OBS;
  hleg(end+1) = plot(ax4, R.along/1e3, R.rp(:,j), '-', 'Color', depth_col{j}, 'LineWidth',2); %#ok<AGROW>
  plot(ax4, R.along(solid)/1e3, R.rp(solid,j), depth_mk{j}, 'MarkerSize',8, ...
    'MarkerFaceColor', depth_col{j}, 'MarkerEdgeColor','w','LineWidth',1);
  plot(ax4, R.along(~solid)/1e3, R.rp(~solid,j), depth_mk{j}, 'MarkerSize',8, ...
    'MarkerFaceColor','w','MarkerEdgeColor', depth_col{j}, 'LineWidth',1.5);
  lbl{end+1} = sprintf('column 0-%.0f m', REF_DEPTHS(j)); %#ok<AGROW>
end
grid(ax4,'on'); set(ax4, axstyle{:}); ylim(ax4,[-1 1]);
xlabel(ax4,'Along track (km)','Color',ink);
ylabel(ax4,'Partial corr. of strain with tide','Color',ink);
title(ax4, sprintf('Tidal response along the line, trend removed (hollow: fewer than %d pairs)', MIN_OBS), ...
  'Color', ink);
lg = legend(ax4, hleg, lbl, 'Location','SouthWest');
set(lg,'TextColor',ink,'Box','off');

out_fn = fullfile(out_dir, sprintf('%s_tidal_deformation%s.png', R.pass_name, R.suffix));
print(h, out_fn, '-dpng', '-r120');
close(h);
fprintf('Wrote %s\n', out_fn);
end

